"""Add audit_logs table

Revision ID: 7664bb61c746
Revises: eb839203e058
Create Date: 2026-04-21 16:23:23.426559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7664bb61c746'
down_revision: Union[str, Sequence[str], None] = 'eb839203e058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Check if constraints exist before dropping them
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Get existing constraints on parent_students table
    constraints = [c['name'] for c in inspector.get_unique_constraints('parent_students')]
    if 'parent_students_parent_id_student_id_key' in constraints:
        op.drop_constraint('parent_students_parent_id_student_id_key', 'parent_students', type_='unique')
    
    # Get existing foreign keys
    fks = [fk['name'] for fk in inspector.get_foreign_keys('parent_students')]
    if 'parent_students_student_id_fkey' in fks:
        op.drop_constraint('parent_students_student_id_fkey', 'parent_students', type_='foreignkey')
    if 'parent_students_parent_id_fkey' in fks:
        op.drop_constraint('parent_students_parent_id_fkey', 'parent_students', type_='foreignkey')
    
    op.create_foreign_key(None, 'parent_students', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'parent_students', 'students', ['student_id'], ['id'])
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'parent_students', type_='foreignkey')
    op.drop_constraint(None, 'parent_students', type_='foreignkey')
    op.create_foreign_key('parent_students_parent_id_fkey', 'parent_students', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('parent_students_student_id_fkey', 'parent_students', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('parent_students_parent_id_student_id_key', 'parent_students', ['parent_id', 'student_id'])
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
